app = 'avatar-ia-back'
primary_region = 'cdg'

[build]
  builder = "paketobuildpacks/builder:base"  # 👈 Ajoute ceci

[http_service]
  internal_port = 3000  # 👈 Assure-toi que ton app écoute sur ce port
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
